import fs from 'node:fs';
import path from 'node:path';
import { config } from '../core/config.js';
import { db } from './db.service.js';
import { logger } from '../core/logger.js';

function sanitizeId(value) {
  return String(value).replace(/[^a-zA-Z0-9_-]/g, '');
}

function buildEndpointHints(endpoints) {
  return endpoints
    .map((endpoint) => {
      const ext = sanitizeId(endpoint.extension);
      const voicemailEnabled = Boolean(endpoint.voicemail_enabled);
      const voicemailBox = sanitizeId(endpoint.voicemail_box || endpoint.extension);
      return [
        `exten => ${ext},1,NoOp(Calling endpoint ${endpoint.display_name || endpoint.extension})`,
        ` same => n,Dial(PJSIP/ext-${ext}-endpoint,20)`,
        voicemailEnabled
          ? ` same => n,Voicemail(${voicemailBox}@default,u)`
          : ' same => n,Hangup()',
        ' same => n,Hangup()',
        ''
      ].join('\n');
    })
    .join('\n');
}

function buildFailoverLine(group) {
  if (group.failover_target) {
    return ` same => n,Goto(internal,${sanitizeId(group.failover_target)},1)`;
  }

  return ' same => n,Voicemail(1000@default,u)';
}

function buildSimultaneousDialLines(memberChannels, timeout) {
  const channels = memberChannels.join('&');
  return [` same => n,Dial(${channels},${timeout})`];
}

function buildLinearDialLines(memberChannels, timeout) {
  const lines = [];
  memberChannels.forEach((channel, index) => {
    const label = index === 0 ? 'first' : `lin${index + 1}`;
    lines.push(` same => n(${label}),Dial(${channel},${timeout})`);
    lines.push(' same => n,GotoIf($["${DIALSTATUS}"="ANSWER"]?done)');
  });
  lines.push(' same => n(done),NoOp(Linear callgroup completed)');
  return lines;
}

function buildRoundRobinDialLines(memberChannels, timeout, groupExt) {
  const lines = [
    ` same => n,Set(GROUPKEY=cg-${groupExt})`,
    ` same => n,Set(MCOUNT=${memberChannels.length})`,
    ' same => n,Set(CURIDX=${DB(callgroup/${GROUPKEY}/idx)})',
    ' same => n,ExecIf($["${CURIDX}"=""]?Set(CURIDX=0))',
    ' same => n,Set(NEXTIDX=$[(${CURIDX}+1)%${MCOUNT}])',
    ' same => n,Set(DB(callgroup/${GROUPKEY}/idx)=${NEXTIDX})'
  ];

  memberChannels.forEach((channel, index) => {
    lines.push(` same => n,GotoIf($["\${CURIDX}"="${index}"]?rr${index + 1})`);
    lines.push(` same => n(rr${index + 1}),Dial(${channel},${timeout})`);
    lines.push(' same => n,GotoIf($["${DIALSTATUS}"="ANSWER"]?done)');
  });

  lines.push(' same => n(done),NoOp(Round-robin callgroup completed)');
  return lines;
}

function buildRandomDialLines(memberChannels, timeout) {
  const lines = [` same => n,Set(RANDIDX=\${RAND(1,${memberChannels.length})})`];
  memberChannels.forEach((channel, index) => {
    lines.push(` same => n,GotoIf($["\${RANDIDX}"="${index + 1}"]?rnd${index + 1})`);
    lines.push(` same => n(rnd${index + 1}),Dial(${channel},${timeout})`);
    lines.push(' same => n,GotoIf($["${DIALSTATUS}"="ANSWER"]?done)');
  });
  lines.push(' same => n(done),NoOp(Random callgroup completed)');
  return lines;
}

function buildCallgroups(callgroups) {
  return callgroups
    .map((group) => {
      const memberChannels = JSON.parse(group.members_json || '[]').map(
        (member) => `PJSIP/ext-${sanitizeId(member)}-endpoint`
      );

      const groupExt = sanitizeId(group.extension);
      const strategy = group.strategy;
      const timeout = Number(group.timeout) || 20;
      const effectiveMembers =
        memberChannels.length > 0 ? memberChannels : ['PJSIP/ext-1000-endpoint'];

      let strategyLines = buildSimultaneousDialLines(effectiveMembers, timeout);
      if (strategy === 'linear') {
        strategyLines = buildLinearDialLines(effectiveMembers, timeout);
      } else if (strategy === 'round-robin') {
        strategyLines = buildRoundRobinDialLines(effectiveMembers, timeout, groupExt);
      } else if (strategy === 'random') {
        strategyLines = buildRandomDialLines(effectiveMembers, timeout);
      }

      return [
        `exten => ${groupExt},1,NoOp(Callgroup ${group.name} strategy=${strategy})`,
        ...strategyLines,
        buildFailoverLine(group),
        ' same => n,Hangup()',
        ''
      ].join('\n');
    })
    .join('\n');
}

export function buildDialplanManagedConfig() {
  const endpoints = db.prepare('SELECT * FROM endpoints ORDER BY extension ASC').all();
  const callgroups = db.prepare('SELECT * FROM callgroups ORDER BY id ASC').all();

  return [
    '; AUTOGENERATED FILE - DO NOT EDIT MANUALLY',
    '; Generated at ' + new Date().toISOString(),
    '',
    '[internal]',
    buildEndpointHints(endpoints),
    '; ---- callgroups ----',
    buildCallgroups(callgroups),
    ''
  ].join('\n');
}

export function writeDialplanManagedConfig() {
  fs.mkdirSync(config.asterisk.configPath, { recursive: true });
  const targetPath = path.join(config.asterisk.configPath, config.asterisk.dialplanManagedFile);
  const tmpPath = `${targetPath}.tmp`;

  const content = buildDialplanManagedConfig();
  fs.writeFileSync(tmpPath, content, 'utf8');
  fs.renameSync(tmpPath, targetPath);

  logger.info('Dialplan managed config written', { targetPath });
  return targetPath;
}
