import fs from 'node:fs';
import path from 'node:path';
import { config } from '../core/config.js';
import { db } from './db.service.js';
import { logger } from '../core/logger.js';

function sanitizeId(value) {
  return String(value).replace(/[^a-zA-Z0-9_-]/g, '');
}

function buildTrunkSections(trunks) {
  return trunks
    .map((trunk) => {
      const trunkId = sanitizeId(trunk.name);
      const endpointName = `trunk-${trunkId}-endpoint`;
      const authName = `trunk-${trunkId}-auth`;
      const aorName = `trunk-${trunkId}-aor`;
      const lines = [
        `[${endpointName}]`,
        'type=endpoint',
        `transport=${trunk.transport || 'udp'}`,
        `context=${trunk.context || 'from-trunk'}`,
        `aors=${aorName}`,
        `outbound_auth=${authName}`,
        `disallow=all`,
        'allow=ulaw,alaw',
        '',
        `[${authName}]`,
        'type=auth',
        'auth_type=userpass',
        `username=${trunk.username || ''}`,
        `password=${trunk.password || ''}`,
        '',
        `[${aorName}]`,
        'type=aor',
        `contact=sip:${trunk.host}`,
        'qualify_frequency=60',
        ''
      ];

      if (trunk.register_enabled) {
        lines.push(`[trunk-${trunkId}-registration]`);
        lines.push('type=registration');
        lines.push(`outbound_auth=${authName}`);
        lines.push(`server_uri=sip:${trunk.host}`);
        lines.push(`client_uri=sip:${trunk.username || trunkId}@${trunk.host}`);
        lines.push(`contact_user=${trunk.username || trunkId}`);
        lines.push('retry_interval=60');
        lines.push('forbidden_retry_interval=300');
        lines.push('expiration=3600');
        lines.push('');
      }

      return lines.join('\n');
    })
    .join('\n');
}

function buildEndpointSections(endpoints) {
  return endpoints
    .map((endpoint) => {
      const ext = sanitizeId(endpoint.extension);
      const endpointName = `ext-${ext}-endpoint`;
      const authName = `ext-${ext}-auth`;
      const aorName = `ext-${ext}-aor`;
      const codecs = (endpoint.codecs || 'ulaw,alaw')
        .split(',')
        .map((codec) => codec.trim())
        .filter(Boolean)
        .join(',');

      return [
        `[${endpointName}]`,
        'type=endpoint',
        'transport=transport-udp',
        `context=${endpoint.context || 'internal'}`,
        `aors=${aorName}`,
        `auth=${authName}`,
        'disallow=all',
        `allow=${codecs || 'ulaw,alaw'}`,
        'direct_media=no',
        '',
        `[${authName}]`,
        'type=auth',
        'auth_type=userpass',
        `username=${endpoint.username}`,
        `password=${endpoint.password}`,
        '',
        `[${aorName}]`,
        'type=aor',
        'max_contacts=5',
        'remove_existing=yes',
        ''
      ].join('\n');
    })
    .join('\n');
}

export function buildPjsipManagedConfig() {
  const trunks = db.prepare('SELECT * FROM trunks ORDER BY id ASC').all();
  const endpoints = db.prepare('SELECT * FROM endpoints ORDER BY extension ASC').all();

  return [
    '; AUTOGENERATED FILE - DO NOT EDIT MANUALLY',
    '; Source of truth: SQLite database managed by asterisk-admin backend',
    '; Generated at ' + new Date().toISOString(),
    '',
    '; ==================== TRUNKS ====================',
    buildTrunkSections(trunks),
    '',
    '; ==================== ENDPOINTS ====================',
    buildEndpointSections(endpoints),
    ''
  ].join('\n');
}

export function writePjsipManagedConfig() {
  fs.mkdirSync(config.asterisk.configPath, { recursive: true });
  const targetPath = path.join(config.asterisk.configPath, config.asterisk.pjsipManagedFile);
  const tmpPath = `${targetPath}.tmp`;

  const content = buildPjsipManagedConfig();
  fs.writeFileSync(tmpPath, content, 'utf8');
  fs.renameSync(tmpPath, targetPath);

  logger.info('PJSIP managed config written', { targetPath });
  return targetPath;
}
